# @format

BOT:
  OWNERS: ["970088877580746782"]
  ADMINS: ["970088877580746782"]

LINKS:
  SUPPORT: "https://discord.com/invite/daEGxSMVRF"
  MONGO_URI: "mongodb+srv://Kronix1:arjun@cluster0.ob9wwsc.mongodb.net/?retryWrites=true&w=majority"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "498f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "970088877580746782"
  TOKEN: "MTI2NDAwNjY0NTkzMTgzNTQyMw.GL37jF.wM0s0UtFfPlpXM8v_Fl_iiZJ2qD77_fbSyu4to"

FUEGO:
  PREFIX: "gmusic!"
  EMOJIS: "black"
  COLOR: "#23272A"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: "MTI2NDAwNjY0NTkzMTgzNTQyMw.GL37jF.wM0s0UtFfPlpXM8v_Fl_iiZJ2qD77_fbSyu4to"
  TOPGGAUTH: ""


WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1264453448166936598/wC_sG-apo9napEKn60SBExN2moW08gVUalsre8xf0SJzfot39Zv73tOfe-Nl1MlueGgO"
  STATIC: "https://discord.com/api/webhooks/1264453448166936598/wC_sG-apo9napEKn60SBExN2moW08gVUalsre8xf0SJzfot39Zv73tOfe-Nl1MlueGgO"
  PLAYER: "https://discord.com/api/webhooks/1264453448166936598/wC_sG-apo9napEKn60SBExN2moW08gVUalsre8xf0SJzfot39Zv73tOfe-Nl1MlueGgO"
  SERVER: "https://discord.com/api/webhooks/1264453448166936598/wC_sG-apo9napEKn60SBExN2moW08gVUalsre8xf0SJzfot39Zv73tOfe-Nl1MlueGgO"
  COMMAND: "https://discord.com/api/webhooks/1264453448166936598/wC_sG-apo9napEKn60SBExN2moW08gVUalsre8xf0SJzfot39Zv73tOfe-Nl1MlueGgO"
